name: LifeCity
description: Projeto Aplicado
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_credit_card: ^4.1.0  
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10
  cached_network_image: ^3.4.0
  form_field_validator: ^1.1.0
  animations: ^2.0.11
  mask_text_input_formatter: ^2.9.0
  provider: ^6.1.2

  flutter_map: any
  latlong2: any
  geolocator: any
  dio: ^5.9.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  intl: ^0.19.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.2.3+1

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/logo.png"
  android: true
  ios: true
  web: false

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo2_1024_1024.png"

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icons/logo2_1024_1024.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/logo2_1024_1024.png"
    background_color: "#ffffff"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/logo2_1024_1024.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/logo2_1024_1024.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
